### ISSUE TITLE
Support fetching Power VS network with regular expression

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes-sigs/cluster-api-provider-ibmcloud#1994]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

A Power VS network can be identified by [id, name or regular expression](https://github.com/Karthik-K-N/cluster-api-provider-ibmcloud/blob/632a722671b28ad67730b94e244c9e479ead999d/api/v1beta2/ibmpowervscluster_types.go#L47-L46), Currently we support both id and name. I would like to have support for fetching network by regular expression.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Karthik-K-N** [comment]
In openshift we mainly use regular expression for identifying a network for reference in machine spec
```
      network:
        regex: ^DHCPSERVER.*ipi-sa04-418nig-jqw97.*_Private$
        type: RegEx
      processorType: Shared
      processors: "0.5"
```

for feature parity I would like to have same support in CAPIBM as well.
