### ISSUE TITLE
cluster-api can not get node by ProviderID

### ISSUE THREAD

**Issue by wentao-zh** [kubernetes-sigs/cluster-api-provider-ibmcloud#304]
/kind bug
/area provider/ibmcloud

**What steps did you take and what happened:**

```
E0104 04:28:13.600248       1 machine_controller_noderef.go:152] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="ibm-vpc-1-md-0-9lc7k"
```

capi-controller-manager reported the error above. And machine PHASE stuck at Provisioning. The status of machine like the following.

```
conditions:
  - lastTransitionTime: "2021-01-03T11:29:37Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-01-03T11:29:16Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-01-03T11:29:37Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2021-01-03T11:31:49Z"
    reason: NodeProvisioning
    severity: Warning
    status: "False"
    type: NodeHealthy
```

**What did you expect to happen:**
Machine status should be ready.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
