### ISSUE TITLE
Allow user to mention both image/network name/id for PowerVS provider

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#431]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**

Currently, the user can specify only the image/network id and not the name,

e.g: current format:

```yaml
  template:
    spec:
      serviceInstanceID: "${IBMPOWERVS_SERVICE_INSTANCE_ID}"
      sshKey: "${IBMPOWERVS_SSHKEY_NAME}"
      imageID: "${IBMPOWERVS_IMAGE_ID}"
      sysType: s922
      procType: shared
      processors: "0.25"
      memory: "8"
      networkID: "${IBMPOWERVS_NETWORK_ID}"
```

PowerVS do accept the name as well for the network/image in the rest apis, so enhancing the spec to speficy both as optional witll be a better solution for the better user experience

Proposal:
```yaml
  template:
    spec:
      serviceInstanceID: "${IBMPOWERVS_SERVICE_INSTANCE_ID}"
      sshKey: "${IBMPOWERVS_SSHKEY_NAME}"
      image:
        id: <>
        name: <>
      sysType: s922
      procType: shared
      processors: "0.25"
      memory: "8"
      network:
        id: <>
        name: <>
```
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/2e6420e747f73410b9cab6d388fbe149d0fa22b7/templates/cluster-template-powervs.yaml#L195:L204

**Anything else you would like to add:**

Similar work is already done in the https://github.com/openshift/cluster-api-provider-powervs/pull/25
