### ISSUE TITLE
Update format of clouds.yaml 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-sigs/cluster-api-provider-ibmcloud#62]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
This is a follow up action for review comments at https://github.com/multicloudlab/cluster-api-provider-ibmcloud/pull/60#discussion_r278823656

We  should keep the format as follows to enable future extension.
```yaml
clouds:
  ibmcloud:
    auth:
      username: "test@test.com"
      password: "here'syourpassword"
```

FYI @xunpan
