### ISSUE TITLE
Publish capi powervs image for 1.24 release for workload clusters

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#708]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Publish capi powervs image for 1.24 release for workload clusters

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by mkumatag** [comment]
New image is built and pushed here for 1.24.2 version, can someone test and lemme know how it goes @Amulyam24 @Karthik-K-N @Prajyot-Parab 

```yaml
Region: us-south
Bucket: power-oss-bucket
Object: capibm-powervs-centos-streams8-1-24-2.ova.gz
```

**Comment by Prajyot-Parab** [comment]
@mkumatag Cluster was successfully create and is in healthy state. However I am unable to ssh into machines (not sure why)

```
prajyotparab@Prajyots-MacBook-Pro cluster-api-provider-ibmcloud % kubectl get nodes -o wide
NAME                            STATUS   ROLES           AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION           CONTAINER-RUNTIME
capi-praj-control-plane-gb8wv   Ready    control-plane   88m   v1.24.2   192.168.167.11   <none>        CentOS Stream 8   4.18.0-394.el8.ppc64le   containerd://1.6.2
capi-praj-md-0-84jsz            Ready    <none>          83m   v1.24.2   192.168.167.12   <none>        CentOS Stream 8   4.18.0-394.el8.ppc64le   containerd://1.6.2
```

```
prajyotparab@Prajyots-MacBook-Pro cluster-api-provider-ibmcloud % ssh -I <PRIVATE_KEY> root@<MACHINE PUBLIC IP>
ssh: connect to host <MACHINE PUBLIC IP> port 22: Connection refused
```

**Comment by mkumatag** [comment]
> prajyotparab@Prajyots-MacBook-Pro cluster-api-provider-ibmcloud % ssh -I <PRIVATE_KEY> root@<MACHINE PUBLIC IP>

This could be because of this issue mentioned here - https://github.com/ppc64le-cloud/pvsadm/issues/283. I think I will have to generate a new base image and then rebuild this image.

**Comment by mkumatag** [comment]
New image is pushed, ptal @Prajyot-Parab 

```yaml
Region: us-south
Bucket: power-oss-bucket
Object: capibm-powervs-centos-streams8-1-24-2-0-1655736789.ova.gz
```
