### ISSUE TITLE
Bump cluster-api version to v1.2.0-beta.0 version

### ISSUE THREAD

**Issue by mkumatag** [kubernetes-sigs/cluster-api-provider-ibmcloud#720]
/kind feature
/area provider/ibmcloud

**Describe the solution you'd like**
Recently there is new pre-release version released for the cluster-api repo here - https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.0-beta.0, lets work on updating to that version

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pashok2398** [comment]
@mkumatag 
Looks like the generated `cluster.yaml` is wrong in `spec.clusterNetwork.pods.cidrBlocks` should looks like:
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
```
Instead of 
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:="192.168.0.0/16"}
```
Currently its generating template like:
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
```
Same issue with `spec.clusterNetwork.services.cidrBlocks`

Not sure its related to cluster-api version...
