### ISSUE TITLE
Error generating cluster.yaml

### ISSUE THREAD

**Issue by pashok2398** [kubernetes-sigs/cluster-api-provider-ibmcloud#725]
/kind bug
/area provider/ibmcloud

Looks like the generated `cluster.yaml` is wrong in `spec.clusterNetwork.pods.cidrBlocks` should looks like:
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
```
Instead of 
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${POD_CIDR:="192.168.0.0/16"}
```
Currently its generating template like:
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - - 192.168.0.0/16
```
Same issue with `spec.clusterNetwork.services.cidrBlocks`

Not sure its related to cluster-api version...
```
clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"1c3a1526f101d4b07d2eec757fe75e8701cf6212", GitTreeState:"clean", BuildDate:"2022-06-03T17:11:09Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Prajyot-Parab** [comment]
@mkumatag IMO - I don't think this should be considered as an error, It is valid acceptable format.

**Comment by Prajyot-Parab** [comment]
```
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - - 192.168.0.0/16
```

also I believe the double dash prefix is a typo here
