### ISSUE TITLE
IBM Cloud Kubernetes Service provider support

### ISSUE THREAD

**Issue by xunpan** [kubernetes-sigs/cluster-api-provider-ibmcloud#86]
/kind feature

**Describe the solution you'd like**
IBM Cloud Kubernetes Service provider support

**Comment by gyliu513** [comment]
@dcberg

**Comment by gyliu513** [comment]
We probably need to integrate with IKS like what openstack is doing now as configured at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh#L139-L141

```yaml
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    cloud-config: /etc/kubernetes/cloud.conf
    cloud-provider: openstack
```

@jichenjc can you help do some investigate for this, since you also worked for https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider before?

@dcberg @rtheis please show your comments if any.

FYI @hchenxa
